name: Deploy to Website

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: lowply/deploy-firebase@v0.0.5
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: likisonlinecorner10

